Repository cloudbees-oss/cjd-jcasc-demo, pull requests merged in 2019-08, with the labels that each got.

#4 Enable Release Drafter for the repository
  .github/release-drafter.yml
Labels: internal

#3 Update Jenkins Configuration-as-Code plugin from 1.24 to 1.25
  plugins.txt
Labels: dependencies

#2 [FNDJEN-1482] - Use Jenkins base image to avoid workaround for Docker packaging limitations
  Dockerfile
  jenkins-support
Labels: enhancement

#5 Add information about release versions to README
  README.md
Labels: documentation

#6 Update JCasC plugin from 1.25 to 1.27
  plugins.txt
Labels: dependencies

#7 Fix the hyperlink in the Docker badge
  README.md
Labels: documentation

#8 Revert to the CJD image after fixing the plugin management scripts in Jenkins docker images
  Dockerfile
Labels: enhancement

#10 Update the Jenkins 2.190 base image as a source of plugin management scripts
  Dockerfile
Labels: dependencies

#16 Use example.com instead of acmecorp for sample URL's
  jenkins.yaml
Labels: enhancement

#13 Use HTML in system message
  jenkins.yaml
Labels: enhancement

#15 Use "inbound agent" instead of "Java Web Start agent" to avoid confusion
  jenkins.yaml
Labels: bug

#12 Hide JENKINS-57326 - don't create bogus jgit
  jenkins.yaml
Labels: bug

#14 Enable the performance optimized pipeline durability
  jenkins.yaml
Labels: enhancement

#11 Force all text files to use Unix EOL
  .gitattributes
Labels: internal
